calendars/urls.py
from django.urls import path

from . import views

app_name = 'calendars'
urlpatterns = [
    path('', views.CalendarListView.as_view(), name='calendar')
]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('frontend/', include('frontend.urls', namespace='frontend')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('teams/', include('teams.urls', namespace='teams')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('evaluations/', include('evaluations.urls', namespace='evaluations')),
    path('meetings/', include('meetings.urls', namespace='meetings')),
    path('calendars/', include('calendars.urls', namespace='calendars')),
]

frontend/urls.py
from django.urls import path

from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.users_register, name='users-register'),
    path('login/', views.users_login, name='users-login'),
    path('users/detail/', views.users_detail, name='users-detail'),
    path('users/list/', views.users_list, name='users-list'),
    path('teams/create/', views.teams_create, name='teams-create'),
    path('teams/list/', views.teams_list, name='teams-list'),
    path('teams/<int:team_id>/change-role/', views.teams_change_role, name='teams-change-role'),
    path('teams/<int:team_id>/update/', views.teams_update, name='teams-update'),
    path('teams/detail/', views.teams_detail, name='teams-detail'),
    path('tasks/<int:team_id>/create/', views.tasks_create, name='tasks-create'),
    path('tasks/admin-list/', views.tasks_admin_list, name='tasks-admin-list'),
    path('tasks/own-list/', views.tasks_own_list, name='tasks-own-list'),
    path('tasks/<int:team_id>/update/<int:pk>/', views.tasks_update, name='tasks-update'),
    path('meetings/create/', views.meetings_create, name='meetings-create'),
    path('meetings/list/', views.meetings_list, name='meetings-list'),
    path('meetings/<int:pk>/update/', views.meetings_update, name='meetings-update'),
    path('calendars/list/', views.calendars_list, name='calendars-list'),
]

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('<int:team_id>/create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:team_id>/update/<int:pk>/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:team_id>/delete/<int:pk>/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:task_id>/add/', views.CommentCreateView.as_view(), name='add-comment'),
    path('own-list/', views.TaskListOwnView.as_view(), name='own-list'),
    path('admin-list/', views.TaskListAdminView.as_view(), name='admin-list'),
]

teams/urls.py
from django.urls import path

from . import views

app_name = 'teams'
urlpatterns = [
    path('create/', views.TeamCreateAPIView.as_view(), name='create'),
    path('delete/<int:pk>', views.TeamDeleteAPIView.as_view(), name='delete'),
    path('add-user/<int:team_id>/', views.TeamAddUserView.as_view(), name='add-user'),
    path('remove-user/', views.TeamRemoveUserView.as_view(), name='remove-user'),
    path('change-role/<int:team_id>/', views.TeamUpdateUserRoleView.as_view(), name='change-role'),
    path('detail/', views.CurrentTeamDetailView.as_view(), name='detail'),
    path('update/<int:pk>', views.TeamUpdateView.as_view(), name='update'),
    path('list/', views.TeamListView.as_view(), name='list')
]

users/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('login/', TokenObtainPairView.as_view(), name='login'),
    path('refresh/', TokenRefreshView.as_view(), name='refresh'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('detail/', views.UserDetailView.as_view(), name='detail'),
    path('list/', views.UserListView.as_view(), name='list'),
    path('update/', views.UserUpdateView.as_view(), name='update'),
    path('delete/<str:email>/', views.UserDeleteView.as_view(), name='delete'),
]

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render, get_object_or_404

from meetings.models import Meeting
from tasks.models import Task
from teams.models import Team


def index(request):
    return render(request, 'index.html')


def users_register(request):
    return render(request, 'users/register.html')


def users_login(request):
    return render(request, 'users/login.html')


def users_detail(request):
    return render(request, 'users/detail.html')


def users_list(request):
    return render(request, 'users/list.html')


def teams_create(request):
    return render(request, 'teams/create.html')


def teams_list(request):
    return render(request, 'teams/list.html')


def teams_change_role(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    return render(request, 'teams/change_role.html', {'team': team})


def teams_update(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    return render(request, 'teams/update.html', {'team': team})


def teams_detail(request):
    return render(request, 'teams/detail.html')


def tasks_create(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    return render(request, 'tasks/create.html', {'team': team})


def tasks_admin_list(request):
    return render(request, 'tasks/admin_list.html')


def tasks_own_list(request):
    return render(request, 'tasks/own_list.html')


def tasks_update(request, team_id, pk):
    task = get_object_or_404(Task, pk=pk, team=team_id)
    return render(request, 'tasks/update.html', {'task': task})

def meetings_create(request):
    return render(request, 'meetings/create.html')

def meetings_list(request):
    return render(request, 'meetings/list.html')

def meetings_update(request, pk):
    meeting = get_object_or_404(Meeting, pk=pk)
    return render(request, 'meetings/update.html', {'meeting': meeting})

def calendars_list(request):
    return render(request, 'calendars/list.html')

frontend/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}
        Final Project
    {% endblock %}</title>
    <script>
        window.APP = {
            user: null
        }
        window.URLS = {
            index: "{% url 'frontend:index' %}",
            login: "{% url 'frontend:users-login' %}",
            register: "{% url 'frontend:users-register' %}",
            userDetail: "{% url 'frontend:users-detail' %}",
            usersList: "{% url 'frontend:users-list' %}",
            teamsCreate: "{% url 'frontend:teams-create' %}",
            teamsList: "{% url 'frontend:teams-list' %}",
            teamsChangeRole: "{% url 'frontend:teams-change-role' 0 %}",
            teamsUpdate: "{% url 'frontend:teams-update' 0 %}",
            teamsDetail: "{% url 'frontend:teams-detail' %}",
            tasksCreate: "{% url 'frontend:tasks-create' 0 %}",
            tasksAdminList: "{% url 'frontend:tasks-admin-list' %}",
            tasksOwnList: "{% url 'frontend:tasks-own-list' %}",
            tasksUpdate: "{% url 'frontend:tasks-update' 0 0 %}",
            meetingsCreate: "{% url 'frontend:meetings-create' %}",
            meetingsList: "{% url 'frontend:meetings-list' %}",
            meetingsUpdate: "{% url 'frontend:meetings-update' 0 %}",
            calendarsList: "{% url 'frontend:calendars-list' %}",

            loginAPI: "{% url 'users:login' %}",
            logoutAPI: "{% url 'users:logout' %}",
            userDetailAPI: "{% url 'users:detail' %}",
            refreshAPI: "{% url 'users:refresh' %}",
            userUpdateAPI: "{% url 'users:update' %}",
            usersListAPI: "{% url 'users:list' %}",
            usersDeleteAPI: "{% url 'users:delete' 'EMAIL_PLACEHOLDER' %}",
            teamsCreateAPI: "{% url 'teams:create' %}",
            teamsListAPI: "{% url 'teams:list' %}",
            teamsDeleteAPI: "{% url 'teams:delete' 0 %}",
            teamsAddUserAPI: "{% url 'teams:add-user' 0 %}",
            teamsRemoveUserAPI: "{% url 'teams:remove-user' %}",
            teamsDetailAPI: "{% url 'teams:detail' %}",
            tasksAdminListAPI: "{% url 'tasks:admin-list' %}",
            tasksOwnListAPI: "{% url 'tasks:own-list' %}",
            tasksUpdateAPI: "{% url 'tasks:update' 0 0 %}",
            tasksDeleteAPI: "{% url 'tasks:delete' 0 0 %}",
            tasksAddCommentAPI: "{% url 'tasks:add-comment' 0 %}",
            evaluationsCreateAPI: "{% url 'evaluations:create' 0 %}",
            evaluationsDeleteAPI: "{% url 'evaluations:delete' 0 %}",
            meetingsCreateAPI: "{% url 'meetings:create' %}",
            meetingsListAPI: "{% url 'meetings:list' %}",
            meetingsUpdateAPI: "{% url 'meetings:update' 0 %}",
            meetingsDeleteAPI: "{% url 'meetings:delete' 0 %}",
            calendarsListAPI: "{% url 'calendars:calendar' %}"
        }
    </script>
    <script defer src="{% static 'js/auth.js' %}"></script>
    <script defer src="{% static 'js/api.js' %}"></script>
    <script defer src="{% static 'js/jwt.js' %}"></script>
    <script defer src="{% static 'js/navbar.js' %}"></script>
</head>
<body>
<header>
    <nav>
        <ul id="navbar">
        </ul>
    </nav>
</header>
<main>
    {% block content %}

    {% endblock %}
</main>
</body>
</html>

frontend/templates/index.html
{% extends 'base.html' %}

{% block title %}
    Главная страница
{% endblock %}

{% block content %}
    <h1>Главная страница</h1>

    <div id="apps-links"></div>

    <script>
        document.addEventListener('DOMContentLoaded', async () => {
            if (!Auth.isAuthenticated()) {
                return;
            }

            const payload = getJwtPayload();

            if (!payload) {
                Auth.logout();
                return;
            }

            if (payload.role === 'admin') {
                html = `
                    <li><a href="${URLS.usersList}">Список пользователей</a></li>
                    <li><a href="${URLS.teamsCreate}">Создать команду</a></li>
                    <li><a href="${URLS.teamsList}">Список команд</a></li>
                    <li><a href="${URLS.tasksAdminList}">Список всех задач</a></li>
                    <li><a href="${URLS.meetingsCreate}">Создать встречу</a></li>
                `;
            }
            html += '</ul>';
            document.getElementById('apps-links').innerHTML = html;
        });
    </script>
{% endblock %}